CREATE TABLE IF NOT EXISTS residents (
    resident_id TEXT PRIMARY KEY,
    nhs_number TEXT,
    name_prefix TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_of_birth DATE,
    gender TEXT,
    care_setting TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    address_city TEXT,
    address_postcode TEXT,
    weight_kg NUMERIC,
    allergies TEXT,
    raw_preferences TEXT[] NOT NULL DEFAULT '{}',
    gp_name TEXT,
    gp_code TEXT,
    source_vendor TEXT,
    source_external_id TEXT,
    source_received_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
