// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'core.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> normalizeMedicationName({required String raw}) =>
    RustLib.instance.api.crateApiNormalizeMedicationName(raw: raw);

Future<Dose?> parseDose({required String raw}) =>
    RustLib.instance.api.crateApiParseDose(raw: raw);

Future<List<MarEntry>> expandSchedule({
  required MedicationOrder order,
  required PlatformInt64 fromTs,
  required PlatformInt64 toTs,
}) => RustLib.instance.api.crateApiExpandSchedule(
  order: order,
  fromTs: fromTs,
  toTs: toTs,
);

Future<List<String>> normalizeReasonCodes({required List<String> list}) =>
    RustLib.instance.api.crateApiNormalizeReasonCodes(list: list);

Future<String> makeEventId() => RustLib.instance.api.crateApiMakeEventId();
