// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Dose {
  final double value;
  final String unit;

  const Dose({required this.value, required this.unit});

  @override
  int get hashCode => value.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Dose &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          unit == other.unit;
}

class MarEntry {
  final String orderId;
  final String residentId;
  final PlatformInt64 scheduledAt;

  const MarEntry({
    required this.orderId,
    required this.residentId,
    required this.scheduledAt,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^ residentId.hashCode ^ scheduledAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarEntry &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          residentId == other.residentId &&
          scheduledAt == other.scheduledAt;
}

class MedicationOrder {
  final String orderId;
  final String residentId;
  final PlatformInt64 intervalMinutes;

  const MedicationOrder({
    required this.orderId,
    required this.residentId,
    required this.intervalMinutes,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^ residentId.hashCode ^ intervalMinutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MedicationOrder &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          residentId == other.residentId &&
          intervalMinutes == other.intervalMinutes;
}
